version: '3.8'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
#     - 51773
# new SuperServerPort
     - 1972
     - 52773
     - 53773
    volumes:
# no key required for community image
#      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/irisdev/app
